# Generated by Django 3.2.4 on 2021-06-15 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SEC_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='period_end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='period_start',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='time_end',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='time_start',
            field=models.TimeField(null=True),
        ),
    ]
