# Generated by Django 3.2.4 on 2021-06-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SEC_App', '0003_alter_request_rangeofsearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tweet_id',
            field=models.TextField(),
        ),
    ]
