# Generated by Django 3.2.4 on 2021-06-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SEC_App', '0004_auto_20210615_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='rangeOfsearch',
            field=models.IntegerField(choices=[(0, '@ALKAHRABA OR @AlkahrabaCare OR كلمة البحث'), (1, 'كلمة البحث فقط')]),
        ),
    ]
