# Generated by Django 3.2.4 on 2021-06-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SEC_App', '0005_alter_request_rangeofsearch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='includeAll',
            field=models.IntegerField(choices=[(0, 'OR'), (1, 'AND')], default=0),
        ),
    ]
