# Generated by Django 3.2.4 on 2021-06-16 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SEC_App', '0006_alter_request_includeall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='date_time',
            field=models.DateTimeField(),
        ),
    ]
