# Generated by Django 3.2.4 on 2021-06-28 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SEC_App', '0007_alter_request_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reactions', models.JSONField()),
                ('period_data', models.JSONField()),
                ('sentiment_data', models.JSONField()),
                ('num_tweets', models.IntegerField()),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEC_App.request')),
            ],
        ),
    ]
