# Generated by Django 3.2.4 on 2021-06-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SEC_App', '0008_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='dtm',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
    ]
