# Generated by Django 3.2.4 on 2021-06-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SEC_App', '0009_analysis_dtm'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='tweets_list',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
    ]
