# Generated by Django 3.2.4 on 2021-06-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SEC_App', '0010_analysis_tweets_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='from_date',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysis',
            name='to_date',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
