# Generated by Django 3.2.4 on 2021-07-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SEC_App', '0011_auto_20210628_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='true_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='true_start',
            field=models.DateField(null=True),
        ),
    ]
