# Generated by Django 3.2.4 on 2021-07-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SEC_App', '0015_alter_request_presentationkeyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='presentationkeyword',
            field=models.TextField(null=True),
        ),
    ]
