# Generated by Django 3.2.4 on 2021-07-07 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SEC_App', '0016_alter_request_presentationkeyword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='presentationkeyword',
        ),
    ]
