# Generated by Django 3.2.4 on 2021-07-07 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SEC_App', '0017_remove_request_presentationkeyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='presentationkeyword',
            field=models.TextField(null=True),
        ),
    ]
