# Generated by Django 3.2.4 on 2021-07-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SEC_App', '0022_alter_request_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='classes_dic',
            field=models.JSONField(default=None, null=True),
        ),
    ]
